---
title: "Graphics with ggplot2"
author: "Sibel"
date: "10/22/2018"
output: html_document
---

# Learning ggplot2

# install and load tidyverse
# install.packages(“tidyverse”)
library(tidyverse)

```{r load.data}
#National Parks in California
ca <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/ca.csv") 

#Acadia National Park
acadia <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/acadia.csv")

#Southeast US National Parks
se <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/se.csv")

#2016 Visitation for all Pacific West National Parks
visit_16 <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/visit_16.csv")

#All Nationally designated sites in Massachusetts
mass <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/mass.csv")
```

```{r}
ggplot(data = ca) +
  geom_point(aes(x = year, y = visitors, color = park_name)) +
  theme_bw() +
  theme(legend.title.align = element_blank())
```
```{r}
ggplot(data = se) +
  geom_point(aes(x = year, y = visitors, color = state)) +
  ggtitle("Visitation by State") +
  theme_minimal() +
  xlab("Year") +
  ylab("Visitors") +
  theme(legend.title = element_blank(),
        axis.text.x = element_text(angle = 45, size = 14))
```



```{r}
ggplot(data = se) +
  geom_point(aes(x = year, y = visitors, color = park_name)) +
  facet_wrap(~ state, scales = "free")
```


```{r}
ggplot(se) +
  geom_line(aes(x = year, y = visitors, color = park_name)) +
  scale_colour_manual(values=cbPalette) +
  theme_classic()
```
```{r}
ggplot(data = acadia, aes(x = year, y = visitors)) +
  geom_point() +
  geom_line() +
  geom_smooth() +
  theme_minimal()
```
```{r}
install.packages("ggthemes")
library(ggthemes)
```


```{r}
ggplot(data = acadia, aes(x = year, y = visitors)) +
  geom_point() +
  geom_line() +
  geom_smooth() +
  theme_classic() +
  scale_colour_manual(values=cbPalette)
```
```{r}
ggplot(data = visit_16, aes(x = state, y = visitors, fill = park_name)) +
  geom_bar(stat = "identity", position = "dodge") +
scale_colour_manual(values=cbPalette)
```
```{r}
install.packages("ggplotly")
```
```{r}
myplot <- ggplot(data = visit_16, aes(x = state, y = visitors, fill = park_name)) +
  geom_bar(stat = "identity", position = "dodge")

myplot

ggsave(filename = "myplot.jpg", myplot, height = 5, width = 5, units = "in")
```

```{r}
library(RcolorBrewer) display.brewer.all()
```
# The palette with grey:
```{r}
cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
```

```{r}
cbbPalette <- c("#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
```


# The palette with black:


# To use for fills, add
  scale_fill_manual(values=cbPalette)

# To use for line and point colors, add
  scale_colour_manual(values=cbPalette)
